### ISSUE TITLE
Despite the description I added, the screen still only shows the message

### ISSUE THREAD

**Issue by daisnkzy** [Code-Forge-Net/remix-toast#16]
login.tsx
` return redirectWithSuccess(
      '/dashboard/expenses',
      {
        message: 'you are login',
        description: 'Yes indeed you are logged in',
      },
      {
        headers: await createUserSession(user),
      }
    );`
root.tsx
`
  useEffect(() => {
    if (toast?.type === 'error') {
      notify.error(toast.message);
    }
    if (toast?.type === 'success') {
      notify.success(toast.message);
    }
    if (toast?.type === 'info') {
      notify.info(toast.message);
    }
  }, [toast]);`

**Comment by daisnkzy** [comment]
I use sonner by the way

**Comment by AlemTuzlak** [comment]
@daisnkzy you still have to pass in the description in, try:
```ts
toast.message('Event has been created', {
  description: toast?.description
})
```

**Comment by daisnkzy** [comment]
@AlemTuzlak  oh i got it,thanks for the answer,you are my hero.
