### ISSUE TITLE
Implement `jsonWith` utility functions

### ISSUE THREAD

**Issue by piotrkulpinski** [Code-Forge-Net/remix-toast#3]
Hi, 
Thanks you for this great library. 
I was thinking if you'd be up for adding JSON utility classes just like you did for redirect. 

The use-case is that sometimes you don't wan't to redirect, just send back some data and show a toast. 

That should be fairly easy to implement.

What do you think?

**Comment by AlemTuzlak** [comment]
Yeah I don't see why not, basically something like this PR:
https://github.com/Code-Forge-Net/remix-toast/pull/2

**Comment by piotrkulpinski** [comment]
Exactly 😅 Nice timing
