### ISSUE TITLE
Show Toast without Redirect

### ISSUE THREAD

**Issue by jwaltz** [Code-Forge-Net/remix-toast#4]
Hi @AlemTuzlak, thank you for the wonderful project!

I was wondering if it is possible to show a toast without utilizing the redirect helpers.

For example, when deleting an item from a list of items I utilize a fetcher and avoid a redirect in accordance with suggested practices. I want to show a toast to the user when the action returns. Is this possible?

Thanks!

**Comment by AlemTuzlak** [comment]
@jwaltz Thank you so much! There is a PR open that adds this functionality and should be merged soon!

**Comment by AlemTuzlak** [comment]
Added!
