### ISSUE TITLE
Setting headers along with toast redirects

### ISSUE THREAD

**Issue by kenn** [Code-Forge-Net/remix-toast#8]
Maybe I'm missing something, but how can I set auth cookies when we  run `redirectWithSuccess`?

```ts
const headers = new Headers();
headers.append("Set-Cookie", await setCookie(AUTH_COOKIE, '...'))
headers.append("Set-Cookie", await setCookie(AUTH_EXP_COOKIE, '...'))

return redirectWithSuccess("/login", "You are logged in!");
```

I thought there would be a third parameter that is compatible with Remix's default `redirect`.

```ts
return redirectWithSuccess("/login", "You are logged in!", { headers });
```

Is there a way to set toast and non-toast headers in one-go?

**Comment by rphlmr** [comment]
The 3rd param takes a `ResponseInit`.
`return redirectWithSuccess("/login", "You are logged in!", { headers });` should work.

**Comment by kenn** [comment]
Ohh that's good to know, thanks!
